// angular/src/app/pages/product/product.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { forkJoin } from 'rxjs';
import { ApiService } from 'src/app/services/api.service';
import { environment } from '../../../environments/environment';
import { Location } from '@angular/common';
import { Toast, ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-product',
  templateUrl: './product.component.html',
  styleUrls: ['./product.component.css'],
})
export class ProductComponent {
  public productData: any;
  public products: any;
  public category: any;
  public subCategory: any;
  public image: any;
  public size: any;
  public currency = '$';
  private lastUrl: string = '';
  public cartItems: number = 0;

  constructor(
    private apiService: ApiService,
    private route: ActivatedRoute,
    private location: Location,
    private toaster: ToastrService
  ) {}

  ngOnInit() {
    this.handleProduct();
    this.apiService.cartItems$.subscribe(
      (item: any) => (this.cartItems = item ?? 0)
    );
  }

  ngAfterViewChecked() {
    const currentUrl = this.location.path();
    if (currentUrl !== this.lastUrl) {
      this.lastUrl = currentUrl;
      this.handleProduct();
    }
  }

  handleProduct() {
    const productId = this.route.snapshot.params['productId'];
    this.apiService.getProduct(productId!).subscribe(
      (data: any) => {
        this.productData = data.product;
        this.image = data.product.image[0];
      },
      (error: any) => {
        console.error('Error fetching posts:', error);
      }
    );
    this.apiService.getProducts().subscribe(
      (data: any) => {
        this.products = data.products.filter((item: any) => {
          if (
            this.category == item.category &&
            this.subCategory === item.subCategory
          ) {
            return item;
          }
        });
      },
      (error: any) => {
        console.error('Error fetching posts:', error);
      }
    );
  }

  setImage(item: string): void {
    this.image = item;
  }

  setSize(item: string): void {
    this.size = item;
  }

  addToCart(id: string, size: string): void {
    this.size = size;
    this.apiService.addProductToCart(id, size).subscribe(
      (data: any) => {
        if (data.success) {
          this.toaster.success(data.message);
          this.apiService.cartItems$.next(this.cartItems + 1);
        } else {
          this.toaster.error(data.message);
        }
      },
      (error: any) => {
        console.error('Error fetching posts:', error);
      }
    );
  }
}

<div
  class="border-t-2 pt-10 transition-opacity ease-in duration-500 opacity-100"
>
  <!-- Product Data -->
  <div class="flex gap-12 sm:gap-12 flex-col sm:flex-row">
    <!-- Product Images -->
    <div class="flex-1 flex flex-col-reverse gap-3 sm:flex-row">
      <div
        class="flex sm:flex-col overflow-x-auto sm:overflow-y-scroll justify-between sm:justify-normal sm:w-[18.7%] w-full"
      >
        <div *ngFor="let item of productData?.image; let i = index">
          <img
            (click)="setImage(item)"
            [src]="item"
            [alt]=""
            class="w-[24%] sm:w-full sm:mb-3 flex-shrink-0 cursor-pointer"
          />
        </div>
      </div>
      <div class="w-full sm:w-[80%]">
        <img [src]="image" [alt]="" class="w-full h-auto" />
      </div>
    </div>

    <!-- Product Info -->
    <div class="flex-1">
      <h1 class="font-medium text-2xl mt-2">{{ productData?.name }}</h1>
      <div class="flex items-center gap-1 mt-2">
        <img
          src="../../../assets/images/star_icon.png"
          [alt]=""
          class="w-3.5"
        />
        <img
          src="../../../assets/images/star_icon.png"
          [alt]=""
          class="w-3.5"
        />
        <img
          src="../../../assets/images/star_icon.png"
          [alt]=""
          class="w-3.5"
        />
        <img
          src="../../../assets/images/star_icon.png"
          [alt]=""
          class="w-3.5"
        />
        <img
          src="../../../assets/images/star_dull_icon.png"
          [alt]=""
          class="w-3.5"
        />
        <p class="pl-2">(122)</p>
      </div>
      <p class="mt-5 text-3xl font-medium">
        {{ currency }}{{ productData?.price }}
      </p>
      <p class="mt-5 text-gray-500 md:w-4/5">
        {{ productData?.description }}
      </p>
      <div class="flex flex-col gap-4 my-8">
        <p>Select Size</p>
        <div class="flex gap-2">
          <button
            *ngFor="let item of productData?.sizes"
            (click)="setSize(item)"
            [ngClass]="{
              'border-black': item == size,
              border: true,
              'py-2 px-4': true,
              'bg-gray-100': true
            }"
            class="border py-2 px-4 bg-gray-100"
          >
            {{ item }}
          </button>
        </div>
      </div>
      <button
        (click)="addToCart(productData?._id, size)"
        class="bg-black text-white px-8 py-3 text-sm active:bg-gray-700"
      >
        ADD TO CART
      </button>
      <hr class="mt-8 sm:w-4/5" />
      <div class="text-sm text-gray-500 mt-5 flex flex-col gap-1">
        <p>100% Original product.</p>
        <p>Cash on delivery is available on this product.</p>
        <p>Easy return and exchange policy within 7 days.</p>
      </div>
    </div>
  </div>

  <!-- Description & Review Section -->
  <div class="mt-20">
    <div class="flex">
      <b class="border px-5 py-3 text-sm">Description</b>
      <p class="border px-5 py-3 text-sm">Reviews (122)</p>
    </div>
    <div class="flex flex-col gap-4 border px-6 py-6 text-sm text-gray-500">
      <p>
        An e-commerce website is an online platform that facilitates the buying
        and selling of products or services over the internet. It serves as a
        virtual marketplace where businesses and individuals can showcase their
        products, interact with customers, and conduct transactions without the
        need for a physical presence. E-commerce websites have gained immense
        popularity due to their convenience, accessibility, and the global reach
        they offer.
      </p>
      <p>
        E-commerce websites typically display products or services along with
        detailed descriptions, images, prices, and any available variations
        (e.g., sizes, colors). Each product usually has its own dedicated page
        with relevant information.
      </p>
    </div>
  </div>

  <!-- Display Related Products -->
  <app-related-products
    [category]="productData?.category"
    [subCategory]="productData?.subCategory"
  ></app-related-products>
</div>

// react/src/pages/Product.jsx
import React, { useContext, useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { ShopContext } from "../context/ShopContext";
import { assets } from "../assets/assets";
import RelatedProducts from "../components/RelatedProducts";

const Product = () => {
  const { productId } = useParams();
  const { products, currency, addToCart } = useContext(ShopContext);
  const [productData, setProductData] = useState(false);
  const [image, setImage] = useState("");
  const [size, setSize] = useState("");

  const fetchProductData = async () => {
    products.map((item) => {
      if (item._id === productId) {
        setProductData(item);
        setImage(item.image[0]);
        return null;
      }
    });
  };

  useEffect(() => {
    fetchProductData();
  }, [productId, products]);

  return productData ? (
    <div className="border-t-2 pt-10 transition-opacity ease-in duration-500 opacity-100">
      {/*----------- Product Data-------------- */}
      <div className="flex gap-12 sm:gap-12 flex-col sm:flex-row">
        {/*---------- Product Images------------- */}
        <div className="flex-1 flex flex-col-reverse gap-3 sm:flex-row">
          <div className="flex sm:flex-col overflow-x-auto sm:overflow-y-scroll justify-between sm:justify-normal sm:w-[18.7%] w-full">
            {productData.image.map((item, index) => (
              <img
                onClick={() => setImage(item)}
                src={item}
                key={index}
                className="w-[24%] sm:w-full sm:mb-3 flex-shrink-0 cursor-pointer"
                alt=""
              />
            ))}
          </div>
          <div className="w-full sm:w-[80%]">
            <img className="w-full h-auto" src={image} alt="" />
          </div>
        </div>

        {/* -------- Product Info ---------- */}
        <div className="flex-1">
          <h1 className="font-medium text-2xl mt-2">{productData.name}</h1>
          <div className=" flex items-center gap-1 mt-2">
            <img src={assets.star_icon} alt="" className="w-3 5" />
            <img src={assets.star_icon} alt="" className="w-3 5" />
            <img src={assets.star_icon} alt="" className="w-3 5" />
            <img src={assets.star_icon} alt="" className="w-3 5" />
            <img src={assets.star_dull_icon} alt="" className="w-3 5" />
            <p className="pl-2">(122)</p>
          </div>
          <p className="mt-5 text-3xl font-medium">
            {currency}
            {productData.price}
          </p>
          <p className="mt-5 text-gray-500 md:w-4/5">
            {productData.description}
          </p>
          <div className="flex flex-col gap-4 my-8">
            <p>Select Size</p>
            <div className="flex gap-2">
              {productData.sizes.map((item, index) => (
                <button
                  onClick={() => setSize(item)}
                  className={`border py-2 px-4 bg-gray-100 ${
                    item === size ? "border-black" : ""
                  }`}
                  key={index}
                >
                  {item}
                </button>
              ))}
            </div>
          </div>
          <button
            onClick={() => addToCart(productData._id, size)}
            className="bg-black text-white px-8 py-3 text-sm active:bg-gray-700"
          >
            ADD TO CART
          </button>
          <hr className="mt-8 sm:w-4/5" />
          <div className="text-sm text-gray-500 mt-5 flex flex-col gap-1">
            <p>100% Original product.</p>
            <p>Cash on delivery is available on this product.</p>
            <p>Easy return and exchange policy within 7 days.</p>
          </div>
        </div>
      </div>

      {/* ---------- Description & Review Section ------------- */}
      <div className="mt-20">
        <div className="flex">
          <b className="border px-5 py-3 text-sm">Description</b>
          <p className="border px-5 py-3 text-sm">Reviews (122)</p>
        </div>
        <div className="flex flex-col gap-4 border px-6 py-6 text-sm text-gray-500">
          <p>
            An e-commerce website is an online platform that facilitates the
            buying and selling of products or services over the internet. It
            serves as a virtual marketplace where businesses and individuals can
            showcase their products, interact with customers, and conduct
            transactions without the need for a physical presence. E-commerce
            websites have gained immense popularity due to their convenience,
            accessibility, and the global reach they offer.
          </p>
          <p>
            E-commerce websites typically display products or services along
            with detailed descriptions, images, prices, and any available
            variations (e.g., sizes, colors). Each product usually has its own
            dedicated page with relevant information.
          </p>
        </div>
      </div>

      {/* --------- display related products ---------- */}

      <RelatedProducts
        category={productData.category}
        subCategory={productData.subCategory}
      />
    </div>
  ) : (
    <div className=" opacity-0"></div>
  );
};

export default Product;
