// angular/src/app/pages/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { ToastrService } from 'ngx-toastr';
import { ApiService } from 'src/app/services/api.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent {
  loginForm: FormGroup;
  currentState: string = 'Login';
  isPasswordVisible: boolean = false;
  token: string | null = localStorage.getItem('token');
  backendUrl: string = 'http://your-backend-url.com'; // Replace with actual backend URL

  constructor(
    private fb: FormBuilder,
    private router: Router,
    private apiService: ApiService,
    private toastr: ToastrService
  ) {
    this.loginForm = this.fb.group({
      name: [''],
      email: ['vir@gmail.com', [Validators.required, Validators.email]],
      password: ['123123', [Validators.required]],
    });
  }

  ngOnInit(): void {
    if (this.token) {
      this.router.navigate(['/']);
    }
  }

  togglePasswordVisibility(): void {
    this.isPasswordVisible = !this.isPasswordVisible;
  }

  onSubmit() {
    if (this.loginForm.invalid) {
      return;
    }
    const { email, password, name } = this.loginForm.value;
    if (this.currentState === 'Sign Up') {
      this.apiService.register({ email, password, name }).subscribe(
        (data: any) => {
          if (data.success) {
            localStorage.setItem('token', data.token);
            this.apiService.token$.next(true);
            this.router.navigate(['/']);
          } else {
            this.toastr.error(data.message);
          }
        },
        (error: any) => {
          this.toastr.error(error);
        }
      );
    } else {
      this.apiService.login({ email, password }).subscribe(
        (data: any) => {
          if (data.success) {
            localStorage.setItem('token', data.token);
            this.apiService.token$.next(true);
            this.router.navigate(['/']);
          } else {
            this.toastr.error(data.message);
          }
        },
        (error: any) => {
          this.toastr.error(error);
        }
      );
    }
  }

  switchState(state: string): void {
    this.currentState = state;
    this.loginForm.reset();
  }
}

<form
  [formGroup]="loginForm"
  (ngSubmit)="onSubmit()"
  class="flex flex-col items-center w-[90%] sm:max-w-96 m-auto mt-14 gap-4 text-gray-800"
>
  <div class="inline-flex items-center gap-2 mb-2 mt-10">
    <p class="prata-regular text-3xl">{{ currentState }}</p>
    <hr class="border-none h-[1.5px] w-8 bg-gray-800" />
  </div>

  <input
    *ngIf="currentState !== 'Login'"
    type="text"
    class="w-full px-3 py-2 border border-gray-800"
    placeholder="Name"
    formControlName="name"
  />
  <input
    type="email"
    class="w-full px-3 py-2 border border-gray-800"
    placeholder="Email"
    formControlName="email"
  />
  <div
    *ngIf="loginForm.get('email')?.invalid && loginForm.get('email')?.touched"
    class="text-red-500 text-sm"
  >
    <div *ngIf="loginForm.get('email')?.hasError('required')">
      Email is required
    </div>
    <div *ngIf="loginForm.get('email')?.hasError('email')">
      Please enter a valid email address
    </div>
  </div>
  <div class="relative container mx-auto">
    <input
      [type]="isPasswordVisible ? 'text' : 'password'"
      class="w-full px-3 py-2 border border-gray-800"
      placeholder="Password"
      formControlName="password"
    />
    <button
      type="button"
      class="absolute inset-y-0 right-0 flex items-center px-4 text-gray-600"
      (click)="togglePasswordVisibility()"
    >
      <ng-container *ngIf="!isPasswordVisible">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          strokeWidth="1.5"
          stroke="currentColor"
          class="w-5 h-5"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M3.98 8.223A10.477 10.477 0 001.934 12C3.226 16.338 7.244 19.5 12 19.5c.993 0 1.953-.138 2.863-.395M6.228 6.228A10.45 10.45 0 0112 4.5c4.756 0 8.773 3.162 10.065 7.498a10.523 10.523 0 01-4.293 5.774M6.228 6.228L3 3m3.228 3.228l3.65 3.65m7.894 7.894L21 21m-3.228-3.228l-3.65-3.65m0 0a3 3 0 10-4.243-4.243m4.242 4.242L9.88 9.88"
          />
        </svg>
      </ng-container>
      <ng-container *ngIf="isPasswordVisible">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          strokeWidth="1.5"
          stroke="currentColor"
          class="w-5 h-5"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z"
          />
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
          />
        </svg>
      </ng-container>
    </button>
  </div>
  <div
    *ngIf="
      loginForm.get('password')?.invalid && loginForm.get('password')?.touched
    "
    class="text-red-500 text-sm mt-2"
  >
    <div *ngIf="loginForm.get('password')?.hasError('required')">
      Password is required
    </div>
  </div>

  <div class="w-full flex justify-between text-sm mt-[-8px]">
    <p class="cursor-pointer">Forgot your password?</p>
    <p
      class="cursor-pointer"
      (click)="switchState(currentState === 'Login' ? 'Sign Up' : 'Login')"
    >
      {{ currentState === "Login" ? "Create account" : "Login Here" }}
    </p>
  </div>

  <button type="submit" class="bg-black text-white font-light px-8 py-2 mt-4">
    {{ currentState === "Login" ? "Sign In" : "Sign Up" }}
  </button>
</form>

// admin/src/components/Login.jsx
import React, { useEffect, useState } from "react";
import { toast } from "react-toastify";
import { Navigate } from "react-router-dom";
import * as adminServices from "../services/AdminServices";
import { useNavigate } from "react-router-dom";

const Login = () => {
  let navigate = useNavigate();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  useEffect(() => {
    if (localStorage.getItem("token")) {
      navigate("/list");
    }
  }, []);

  const onSubmitHandler = async (e) => {
    try {
      e.preventDefault();
      const response = await adminServices.login(email, password);
      if (response.data.success) {
        localStorage.setItem("token", response.data.token);
        navigate("/list");
      } else {
        toast.error(response.data.message);
      }
    } catch (error) {
      toast.error(error.message);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center w-full">
      <div className="bg-white shadow-md rounded-lg px-8 py-6 max-w-md">
        <h1 className="text-2xl font-bold mb-4">Admin Panel</h1>
        <form onSubmit={onSubmitHandler}>
          <div className="mb-3 min-w-72">
            <p className="text-sm font-medium text-gray-700 mb-2">
              Email Address
            </p>
            <input
              onChange={(e) => setEmail(e.target.value)}
              value={email}
              className="rounded-md w-full px-3 py-2 border border-gray-300 outline-none"
              type="email"
              placeholder="your@email.com"
              required
            />
          </div>
          <div className="mb-3 min-w-72">
            <p className="text-sm font-medium text-gray-700 mb-2">Password</p>
            <input
              onChange={(e) => setPassword(e.target.value)}
              value={password}
              className="rounded-md w-full px-3 py-2 border border-gray-300 outline-none"
              type="password"
              placeholder="Enter your password"
              required
            />
          </div>
          <button
            className="mt-2 w-full py-2 px-4 rounded-md text-white bg-black"
            type="submit"
          >
            {" "}
            Login{" "}
          </button>
        </form>
      </div>
    </div>
  );
};

export default Login;
