// angular/src/app/components/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { ApiService } from 'src/app/services/api.service';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css'],
})
export class NavbarComponent {
  public visible = false;
  public token: any = localStorage.getItem('token');
  public assets: any;
  public cartItems: any = null;
  navLinks = [
    { label: 'HOME', path: '/' },
    { label: 'COLLECTION', path: '/collection' },
    { label: 'ABOUT', path: '/about' },
    { label: 'CONTACT', path: '/contact' },
  ];

  constructor(private router: Router, private apiService: ApiService) {}

  ngOnInit() {
    this.apiService.token$.subscribe((token: any) => {
      this.token = token;
    });
    this.apiService.cartItems$.subscribe(
      (item: any) => (this.cartItems = item)
    );
  }

  toggleSidebar() {
    this.visible = !this.visible;
  }

  onSearchClick() {
    this.router.navigate(['/collection']);
    this.apiService.showSearchbar$.next(true);
  }

  onProfileClick() {
    if (!this.token) {
      this.router.navigate(['/login']);
    }
  }

  navigateToOrders() {
    this.router.navigate(['/orders']);
  }

  logout() {
    this.token = null;
    localStorage.removeItem('token');
    this.apiService.token$.next(null);
    this.router.navigate(['/login']);
  }
}

<div class="flex items-center justify-between py-5 font-medium">
  <a href="/" class="flex items-center">
    <img src="../../../assets/images/logo.png" class="w-36" alt="" />
  </a>

  <ul *ngIf="token" class="hidden sm:flex gap-5 text-sm text-gray-700">
    <li *ngFor="let link of navLinks" class="flex flex-col items-center gap-1">
      <a
        [routerLink]="link.path"
        routerLinkActive="active"
        [routerLinkActiveOptions]="{ exact: true }"
        class="flex flex-col items-center gap-1"
      >
        <p>{{ link.label }}</p>
        <hr class="w-2/4 border-none h-[1.5px] bg-gray-700 hidden" />
      </a>
    </li>
  </ul>

  <div *ngIf="token" class="flex items-center gap-6">
    <img
      (click)="onSearchClick()"
      src="../../../assets/images/search_icon.png"
      class="w-5 cursor-pointer"
      alt=""
    />

    <a href="/cart" class="relative">
      <img
        src="../../../assets/images/cart_icon.png"
        class="w-5 min-w-5"
        alt=""
      />
      <p
        *ngIf="cartItems"
        class="absolute right-[-5px] bottom-[-5px] w-4 text-center leading-4 bg-black text-white aspect-square rounded-full text-[8px]"
      >
        {{ cartItems }}
      </p>
    </a>

    <img
      (click)="toggleSidebar()"
      src="../../../assets/images/menu_icon.png"
      class="w-5 cursor-pointer sm:hidden"
      alt=""
    />
    <div class="group relative">
      <img
        (click)="onProfileClick()"
        class="w-5 cursor-pointer"
        src="../../../assets/images/profile_icon.png"
        alt=""
      />
      <!-- Dropdown Menu -->
      <div
        *ngIf="token"
        class="group-hover:block hidden absolute dropdown-menu right-0 pt-4"
      >
        <div
          class="flex flex-col gap-2 w-36 py-3 px-5 bg-slate-100 text-gray-500 rounded"
        >
          <p class="cursor-pointer hover:text-black">My Profile</p>
          <p
            (click)="navigateToOrders()"
            class="cursor-pointer hover:text-black"
          >
            Orders
          </p>
          <p (click)="logout()" class="cursor-pointer hover:text-black">
            Logout
          </p>
        </div>
      </div>
    </div>
  </div>

  <!-- Sidebar menu for small screens -->
  <div
    [ngClass]="{ 'w-full': visible, 'w-0': !visible }"
    class="absolute top-0 right-0 bottom-0 overflow-hidden bg-white transition-all"
  >
    <div class="flex flex-col text-gray-600">
      <div
        (click)="toggleSidebar()"
        class="flex items-center gap-4 p-3 cursor-pointer"
      >
        <img
          class="h-4 rotate-180"
          src="../../../assets/images/dropdown_icon.png"
          alt=""
        />
        <p>Back</p>
      </div>

      <a
        *ngFor="let link of navLinks"
        (click)="toggleSidebar()"
        [routerLink]="link.path"
        class="py-2 pl-6 border"
      >
        {{ link.label }}
      </a>
    </div>
  </div>
</div>

// react/src/components/Navbar.jsx
import React, { useContext, useState } from "react";
import { assets } from "../assets/assets";
import { Link, NavLink } from "react-router-dom";
import { ShopContext } from "../context/ShopContext";

const Navbar = () => {
  const [visible, setVisible] = useState(false);

  const {
    setShowSearch,
    getCartCount,
    navigate,
    token,
    setToken,
    setCartItems,
  } = useContext(ShopContext);

  const logout = () => {
    navigate("/login");
    localStorage.removeItem("token");
    setToken("");
    setCartItems({});
  };

  return (
    <div className="flex items-center justify-between py-5 font-medium">
      <Link to="/">
        <img src={assets.logo} className="w-36" alt="" />
      </Link>
      {token !== "" && (
        <>
          <ul className="hidden sm:flex gap-5 text-sm text-gray-700">
            <NavLink to="/" className="flex flex-col items-center gap-1">
              <p>HOME</p>
              <hr className="w-2/4 border-none h-[1.5px] bg-gray-700 hidden" />
            </NavLink>
            <NavLink
              to="/collection"
              className="flex flex-col items-center gap-1"
            >
              <p>COLLECTION</p>
              <hr className="w-2/4 border-none h-[1.5px] bg-gray-700 hidden" />
            </NavLink>
            <NavLink to="/about" className="flex flex-col items-center gap-1">
              <p>ABOUT</p>
              <hr className="w-2/4 border-none h-[1.5px] bg-gray-700 hidden" />
            </NavLink>
            <NavLink to="/contact" className="flex flex-col items-center gap-1">
              <p>CONTACT</p>
              <hr className="w-2/4 border-none h-[1.5px] bg-gray-700 hidden" />
            </NavLink>
          </ul>

          <div className="flex items-center gap-6">
            <img
              onClick={() => {
                setShowSearch(true);
                navigate("/collection");
              }}
              src={assets.search_icon}
              className="w-5 cursor-pointer"
              alt=""
            />
            <Link to="/cart" className="relative">
              <img src={assets.cart_icon} className="w-5 min-w-5" alt="" />
              <p className="absolute right-[-5px] bottom-[-5px] w-4 text-center leading-4 bg-black text-white aspect-square rounded-full text-[8px]">
                {getCartCount()}
              </p>
            </Link>
            <div className="group relative">
              <img
                onClick={() => (token ? null : navigate("/login"))}
                className="w-5 cursor-pointer"
                src={assets.profile_icon}
                alt=""
              />
              {/* Dropdown Menu */}
              {token && (
                <div className="group-hover:block hidden absolute dropdown-menu right-0 pt-4">
                  <div className="flex flex-col gap-2 w-36 py-3 px-5  bg-slate-100 text-gray-500 rounded">
                    <p className="cursor-pointer hover:text-black">
                      My Profile
                    </p>
                    <p
                      onClick={() => navigate("/orders")}
                      className="cursor-pointer hover:text-black"
                    >
                      Orders
                    </p>
                    <p
                      onClick={logout}
                      className="cursor-pointer hover:text-black"
                    >
                      Logout
                    </p>
                  </div>
                </div>
              )}
            </div>
            <img
              onClick={() => setVisible(true)}
              src={assets.menu_icon}
              className="w-5 cursor-pointer sm:hidden"
              alt=""
            />
          </div>
          {/* Sidebar menu for small screens */}
          <div
            className={`absolute top-0 right-0 bottom-0 overflow-hidden bg-white transition-all ${
              visible ? "w-full" : "w-0"
            }`}
          >
            <div className="flex flex-col text-gray-600">
              <div
                onClick={() => setVisible(false)}
                className="flex items-center gap-4 p-3 cursor-pointer"
              >
                <img
                  className="h-4 rotate-180"
                  src={assets.dropdown_icon}
                  alt=""
                />
                <p>Back</p>
              </div>
              <NavLink
                onClick={() => setVisible(false)}
                className="py-2 pl-6 border"
                to="/"
              >
                HOME
              </NavLink>
              <NavLink
                onClick={() => setVisible(false)}
                className="py-2 pl-6 border"
                to="/collection"
              >
                COLLECTION
              </NavLink>
              <NavLink
                onClick={() => setVisible(false)}
                className="py-2 pl-6 border"
                to="/about"
              >
                ABOUT
              </NavLink>
              <NavLink
                onClick={() => setVisible(false)}
                className="py-2 pl-6 border"
                to="/contact"
              >
                CONTACT
              </NavLink>
            </div>
          </div>
        </>
      )}
    </div>
  );
};

export default Navbar;
