// admin/src/pages/Orders.jsx
import React from "react";
import { useEffect } from "react";
import { useState } from "react";
import { currency } from "../App";
import { toast } from "react-toastify";
import { assets } from "../assets/assets";
import * as adminServices from "../services/AdminServices";

const Orders = () => {
  const [orders, setOrders] = useState([]);

  const fetchAllOrders = async () => {
    try {
      const response = await adminServices.getOrders();
      if (response.data.success) {
        setOrders(response.data.orders.reverse());
      } else {
        toast.error(response.data.message);
      }
    } catch (error) {
      toast.error(error.message);
    }
  };

  const statusHandler = async (event, orderId) => {
    try {
      const response = await adminServices.getOrderStatus(
        orderId,
        event.target.value
      );
      if (response.data.success) {
        await fetchAllOrders();
      }
    } catch (error) {
      console.log(error);
      toast.error(error.message);
    }
  };

  useEffect(() => {
    fetchAllOrders();
  }, []);

  return (
    <div>
      <h3>Order Page</h3>
      <div>
        {orders.map((order, index) => (
          <div
            className="grid grid-cols-1 sm:grid-cols-[0.5fr_2fr_1fr] lg:grid-cols-[0.5fr_2fr_1fr_1fr_1fr] gap-3 items-start border-2 border-gray-200 p-5 md:p-8 my-3 md:my-4 text-xs sm:text-sm text-gray-700"
            key={index}
          >
            <img className="w-12" src={assets.parcel_icon} alt="" />
            <div>
              <div>
                {order.items.map((item, index) => {
                  if (index === order.items.length - 1) {
                    return (
                      <p className="py-0.5" key={index}>
                        {" "}
                        {item.name} x {item.quantity} <span> {item.size} </span>{" "}
                      </p>
                    );
                  } else {
                    return (
                      <p className="py-0.5" key={index}>
                        {" "}
                        {item.name} x {item.quantity} <span> {item.size} </span>{" "}
                        ,
                      </p>
                    );
                  }
                })}
              </div>
              <p className="mt-3 mb-2 font-medium">
                {order.address.firstName + " " + order.address.lastName}
              </p>
              <div>
                <p>{order.address.street + ","}</p>
                <p>
                  {order.address.city +
                    ", " +
                    order.address.state +
                    ", " +
                    order.address.country +
                    ", " +
                    order.address.zipcode}
                </p>
              </div>
              <p>{order.address.phone}</p>
            </div>
            <div>
              <p className="text-sm sm:text-[15px]">
                Items : {order.items.length}
              </p>
              <p className="mt-3">Method : {order.paymentMethod}</p>
              <p>Payment : {order.payment ? "Done" : "Pending"}</p>
              <p>Date : {new Date(order.date).toLocaleDateString()}</p>
            </div>
            <p className="text-sm sm:text-[15px]">
              {currency}
              {order.amount}
            </p>
            <select
              onChange={(event) => statusHandler(event, order._id)}
              value={order.status}
              className="p-2 font-semibold"
            >
              <option value="Order Placed">Order Placed</option>
              <option value="Packing">Packing</option>
              <option value="Shipped">Shipped</option>
              <option value="Out for delivery">Out for delivery</option>
              <option value="Delivered">Delivered</option>
            </select>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Orders;

// angular/src/app/pages/orders/orders.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { ToastrService } from 'ngx-toastr';
import { ApiService } from 'src/app/services/api.service';

@Component({
  selector: 'app-orders',
  templateUrl: './orders.component.html',
  styleUrls: ['./orders.component.css'],
})
export class OrdersComponent {
  constructor(
    private apiService: ApiService,
    private toaster: ToastrService,
    private router: Router
  ) {}

  public currency = '$';
  public orderData: any = [];

  ngOnInit() {
    this.apiService.getOrders().subscribe(
      (data: any) => {
        if (data.success) {
          let orders: any = [];
          data.orders.map((order: any) => {
            order.items.map((cart: any) => {
              cart['status'] = order.status;
              cart['payment'] = order.payment;
              cart['paymentMethod'] = order.paymentMethod;
              cart['date'] = order.date;
              orders.push(cart);
            });
          });
          this.orderData = orders;
        } else {
          this.toaster.error(data.message);
        }
      },
      (error: any) => {
        console.error('Error fetching posts:', error);
      }
    );
  }
}

<!-- my-orders.component.html -->
<div class="border-t pt-16">
  <div class="text-2xl">
    <app-title [text1]="'MY'" [text2]="'ORDERS'"></app-title>
  </div>

  <div>
    <div
      *ngFor="let item of orderData; let index = index"
      class="py-4 border-t border-b text-gray-700 flex flex-col md:flex-row md:items-center md:justify-between gap-4"
    >
      <div class="flex items-start gap-6 text-sm">
        <img class="w-16 sm:w-20" [src]="item.image[0]" alt="" />
        <div>
          <p class="sm:text-base font-medium">{{ item.name }}</p>
          <div class="flex items-center gap-3 mt-1 text-base text-gray-700">
            <p>{{ currency }}{{ item.price }}</p>
            <p>Quantity: {{ item.quantity }}</p>
            <p>Size: {{ item.size }}</p>
          </div>
          <p class="mt-1">
            Date:
            <span class="text-gray-400">{{
              item.date | date : "shortDate"
            }}</span>
          </p>
          <p class="mt-1">
            Payment: <span class="text-gray-400">{{ item.paymentMethod }}</span>
          </p>
        </div>
      </div>
      <div class="md:w-1/2 flex justify-between">
        <div class="flex items-center gap-2">
          <p class="min-w-2 h-2 rounded-full bg-green-500"></p>
          <p class="text-sm md:text-base">{{ item.status }}</p>
        </div>
        <button class="border px-4 py-2 text-sm font-medium rounded-sm">
          Track Order
        </button>
      </div>
    </div>
  </div>
</div>
