// react/src/pages/Orders.jsx
import React, { useContext, useEffect, useState } from "react";
import { ShopContext } from "../context/ShopContext";
import Title from "../components/Title";
import axios from "axios";

const Orders = () => {
  const { backendUrl, token, currency } = useContext(ShopContext);
  const [orderData, setorderData] = useState([]);

  const loadOrderData = async () => {
    try {
      if (!token) {
        return null;
      }

      const response = await axios.post(
        backendUrl + "/api/order/userorders",
        {},
        { headers: { token } }
      );
      if (response.data.success) {
        let allOrdersItem = [];
        response.data.orders.map((order) => {
          order.items.map((item) => {
            item["status"] = order.status;
            item["payment"] = order.payment;
            item["paymentMethod"] = order.paymentMethod;
            item["date"] = order.date;
            allOrdersItem.push(item);
          });
        });
        setorderData(allOrdersItem.reverse());
      }
    } catch (error) {
      /* empty */
    }
  };

  useEffect(() => {
    loadOrderData();
  }, [token]);

  return (
    <div className="border-t pt-16">
      <div className="text-2xl">
        <Title text1={"MY"} text2={"ORDERS"} />
      </div>

      <div>
        {orderData.map((item, index) => (
          <div
            key={index}
            className="py-4 border-t border-b text-gray-700 flex flex-col md:flex-row md:items-center md:justify-between gap-4"
          >
            <div className="flex items-start gap-6 text-sm">
              <img className="w-16 sm:w-20" src={item.image[0]} alt="" />
              <div>
                <p className="sm:text-base font-medium">{item.name}</p>
                <div className="flex items-center gap-3 mt-1 text-base text-gray-700">
                  <p>
                    {currency}
                    {item.price}
                  </p>
                  <p>Quantity: {item.quantity}</p>
                  <p>Size: {item.size}</p>
                </div>
                <p className="mt-1">
                  Date:{" "}
                  <span className=" text-gray-400">
                    {new Date(item.date).toDateString()}
                  </span>
                </p>
                <p className="mt-1">
                  Payment:{" "}
                  <span className=" text-gray-400">{item.paymentMethod}</span>
                </p>
              </div>
            </div>
            <div className="md:w-1/2 flex justify-between">
              <div className="flex items-center gap-2">
                <p className="min-w-2 h-2 rounded-full bg-green-500"></p>
                <p className="text-sm md:text-base">{item.status}</p>
              </div>
              <button
                onClick={loadOrderData}
                className="border px-4 py-2 text-sm font-medium rounded-sm"
              >
                Track Order
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Orders;

// angular/src/app/pages/orders/orders.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { ToastrService } from 'ngx-toastr';
import { ApiService } from 'src/app/services/api.service';

@Component({
  selector: 'app-orders',
  templateUrl: './orders.component.html',
  styleUrls: ['./orders.component.css'],
})
export class OrdersComponent {
  constructor(
    private apiService: ApiService,
    private toaster: ToastrService,
    private router: Router
  ) {}

  public currency = '$';
  public orderData: any = [];

  ngOnInit() {
    this.apiService.getOrders().subscribe(
      (data: any) => {
        if (data.success) {
          let orders: any = [];
          data.orders.map((order: any) => {
            order.items.map((cart: any) => {
              cart['status'] = order.status;
              cart['payment'] = order.payment;
              cart['paymentMethod'] = order.paymentMethod;
              cart['date'] = order.date;
              orders.push(cart);
            });
          });
          this.orderData = orders;
        } else {
          this.toaster.error(data.message);
        }
      },
      (error: any) => {
        console.error('Error fetching posts:', error);
      }
    );
  }
}

<!-- my-orders.component.html -->
<div class="border-t pt-16">
  <div class="text-2xl">
    <app-title [text1]="'MY'" [text2]="'ORDERS'"></app-title>
  </div>

  <div>
    <div
      *ngFor="let item of orderData; let index = index"
      class="py-4 border-t border-b text-gray-700 flex flex-col md:flex-row md:items-center md:justify-between gap-4"
    >
      <div class="flex items-start gap-6 text-sm">
        <img class="w-16 sm:w-20" [src]="item.image[0]" alt="" />
        <div>
          <p class="sm:text-base font-medium">{{ item.name }}</p>
          <div class="flex items-center gap-3 mt-1 text-base text-gray-700">
            <p>{{ currency }}{{ item.price }}</p>
            <p>Quantity: {{ item.quantity }}</p>
            <p>Size: {{ item.size }}</p>
          </div>
          <p class="mt-1">
            Date:
            <span class="text-gray-400">{{
              item.date | date : "shortDate"
            }}</span>
          </p>
          <p class="mt-1">
            Payment: <span class="text-gray-400">{{ item.paymentMethod }}</span>
          </p>
        </div>
      </div>
      <div class="md:w-1/2 flex justify-between">
        <div class="flex items-center gap-2">
          <p class="min-w-2 h-2 rounded-full bg-green-500"></p>
          <p class="text-sm md:text-base">{{ item.status }}</p>
        </div>
        <button class="border px-4 py-2 text-sm font-medium rounded-sm">
          Track Order
        </button>
      </div>
    </div>
  </div>
</div>
